Workflow : add android

diff --git a/.github/workflows/cmake-multi-platform.yml b/.github/workflows/cmake-multi-platform.yml
--- a/.github/workflows/cmake-multi-platform.yml
+++ b/.github/workflows/cmake-multi-platform.yml
@@ -1,6 +1,4 @@
-# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
-# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
-name: CMake on multiple platforms
+name: CMake + Gradle Build (Windows, Linux, Android)
 
 on:
   push:
@@ -13,66 +11,103 @@ jobs:
     runs-on: ${{ matrix.os }}
 
     strategy:
-      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
       fail-fast: false
-
-      # Set up a matrix to run the following 3 configurations:
-      # 1. <Windows, Release, latest MSVC compiler toolchain on the default runner image, default generator>
-      # 2. <Linux, Release, latest GCC compiler toolchain on the default runner image, default generator>
-      # 3. <Linux, Release, latest Clang compiler toolchain on the default runner image, default generator>
-      #
-      # To add more build types (Release, Debug, RelWithDebInfo, etc.) customize the build_type list.
       matrix:
-        os: [ubuntu-latest, windows-latest]
-        build_type: [Release]
-        c_compiler: [gcc, clang, cl]
         include:
           - os: windows-latest
             c_compiler: cl
             cpp_compiler: cl
+            build_type: Release
+            target: windows
+
           - os: ubuntu-latest
             c_compiler: gcc
             cpp_compiler: g++
+            build_type: Release
+            target: linux
+
           - os: ubuntu-latest
             c_compiler: clang
             cpp_compiler: clang++
-        exclude:
-          - os: windows-latest
-            c_compiler: gcc
-          - os: windows-latest
-            c_compiler: clang
+            build_type: Release
+            target: linux
+
           - os: ubuntu-latest
-            c_compiler: cl
+            build_type: Release
+            target: android
 
     steps:
     - uses: actions/checkout@v4
 
     - name: Set reusable strings
-      # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
       id: strings
       shell: bash
       run: |
         echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
-        
-    - name: Setup Build Environnement Linux
+
+    - name: Cache Linux dependencies
+      if: matrix.os == 'ubuntu-latest' && matrix.target == 'linux'
+      uses: actions/cache@v3
+      with:
+        path: /var/cache/apt
+        key: ${{ runner.os }}-apt-${{ hashFiles('**/apt-requirements.txt') }}
+        restore-keys: |
+          ${{ runner.os }}-apt-
+
+    - name: Setup Linux dependencies
+      if: matrix.os == 'ubuntu-latest' && matrix.target == 'linux'
       run: |
         sudo apt update
-        sudo apt install -y --no-install-recommends libglu1-mesa-dev libxcursor-dev libxi-dev libxinerama-dev
-        sudo apt install -y --no-install-recommends libxrandr-dev libxrender-dev libxss-dev libxxf86vm-dev
-        sudo apt install -y --no-install-recommends libasound2-dev libpulse-dev libibus-1.0-dev
-        sudo apt install -y --no-install-recommends libdbus-1-dev libreadline6-dev libssl-dev libudev-dev
-      if: matrix.os == 'ubuntu-latest'
-      
-    - name: Setup Build Environment Windows
+        # check cache if restored
+        if [ -d "/var/cache/apt/archives" ]; then
+          echo "Restored Cache."
+        else
+          sudo apt install -y --no-install-recommends \
+            libglu1-mesa-dev libxcursor-dev libxi-dev libxinerama-dev \
+            libxrandr-dev libxrender-dev libxss-dev libxxf86vm-dev \
+            libasound2-dev libpulse-dev libibus-1.0-dev \
+            libdbus-1-dev libreadline6-dev libssl-dev libudev-dev
+        fi
+
+    - name: Cache Chocolatey packages
+      if: matrix.os == 'windows-latest'
+      uses: actions/cache@v3
+      with:
+        path: C:\ProgramData\chocolatey\bin
+        key: ${{ runner.os }}-choco-${{ hashFiles('**/choco-requirements.txt') }}
+        restore-keys: |
+          ${{ runner.os }}-choco-
+
+    - name: Setup Windows dependencies
+      if: matrix.os == 'windows-latest'
       shell: bash
       run: |
-        # Install OpenSSL using Chocolatey
-        choco install openssl -y
-      if: matrix.os == 'windows-latest'
-      
-    - name: Configure CMake
-      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
-      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
+        # check cache if restored
+        if [ -d "C:\ProgramData\chocolatey\bin" ]; then
+          echo "Restored Cache."
+        else
+          choco install openssl -y
+        fi
+
+    - name: Export Keystore Info
+      if: matrix.target == 'android'
+      run: |
+        echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> $GITHUB_ENV
+        echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> $GITHUB_ENV
+        echo "KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> $GITHUB_ENV
+        echo "KEYSTORE_FILE=release.keystore" >> $GITHUB_ENV
+        echo "${{ secrets.KEYSTORE_FILE }}" | base64 -d > release.keystore || { echo "Keystore decoding failed"; exit 1; }
+
+    - name: Make gradlew executable
+      if: matrix.target == 'android'
+      run: chmod +x ./gradlew
+
+    - name: Build APK with Gradle
+      if: matrix.target == 'android'
+      run: ./gradlew assembleRelease
+
+    - name: Configure CMake (Linux/Windows)
+      if: matrix.target != 'android'
       run: >
         cmake -B ${{ steps.strings.outputs.build-output-dir }}
         -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
@@ -80,12 +115,19 @@ jobs:
         -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
         -S ${{ github.workspace }}
 
-    - name: Build
-      # Build your program with the given configuration. Note that --config is needed because the default Windows generator is a multi-config generator (Visual Studio generator).
+    - name: Build (Linux/Windows)
+      if: matrix.target != 'android'
       run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}
 
-    - name: Test
+    - name: Test (Linux/Windows)
+      if: matrix.target != 'android'
       working-directory: ${{ steps.strings.outputs.build-output-dir }}
-      # Execute tests defined by the CMake configuration. Note that --build-config is needed because the default Windows generator is a multi-config generator (Visual Studio generator).
-      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
       run: ctest --build-config ${{ matrix.build_type }}
+
+    - name: Upload APK artifact
+      if: matrix.target == 'android'
+      uses: actions/upload-artifact@v4
+      with:
+        name: android-apk
+        path: app/build/outputs/apk/release/*.apk
+
